spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: root
  sql:
    init:
      mode: ALWAYS
      continue-on-error: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
